# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vm-DwxVvjrkT_Tw1JcZz3pg4QIjkR7N
"""

from flask import Flask, request, jsonify
import joblib
import numpy as np

app = Flask(__name__)

# تحميل الموديل
model = joblib.load('../models/heart_model.pkl')

@app.route('/')
def home():
    return "Heart Disease API is running"

@app.route('/predict', methods=['POST'])
def predict():
    data = request.json  # JSON input

    # تحويل البيانات إلى array
    features = np.array(data['features']).reshape(1, -1)

    prediction = model.predict(features)

    return jsonify({
        "prediction": int(prediction[0])
    })

if __name__ == '__main__':
    app.run(debug=True)